// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgQiN4A6Wy6Ug_Fk1lV6d2a4UEpiGAmhg',
    appId: '1:923254007203:web:4bb9262ec845fd7ce6a616',
    messagingSenderId: '923254007203',
    projectId: 'instagram-clone-1b720',
    authDomain: 'instagram-clone-1b720.firebaseapp.com',
    storageBucket: 'instagram-clone-1b720.appspot.com',
    measurementId: 'G-KJJ3E7MX84',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDn-GwMZhHDgzeck2hnZ-Ye3jknPzDPZs',
    appId: '1:923254007203:android:a86bf29b39b3d453e6a616',
    messagingSenderId: '923254007203',
    projectId: 'instagram-clone-1b720',
    storageBucket: 'instagram-clone-1b720.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCO9dMlvrVuouTY0R3YkqT6HT3-bBIFAyQ',
    appId: '1:923254007203:ios:43a103465eaed585e6a616',
    messagingSenderId: '923254007203',
    projectId: 'instagram-clone-1b720',
    storageBucket: 'instagram-clone-1b720.appspot.com',
    iosBundleId: 'com.example.instagramFlutter',
  );
}
